const comments = [
  "Great post! Really enjoyed reading it.",
  "Very informative. Thanks for sharing!",
  "This is fantastic information. I learned a lot.",
  "Awesome content! Keep up the good work.",
  "I love how detailed this post is.",
  "Wow, I never knew about this before. Thanks!",
  "Such a helpful post. Will definitely come back for more.",
  "Excellent breakdown of the topic. Well done!",
  "This was a pleasure to read. Well-written!",
  "Thank you for providing such valuable insights.",
  "Really appreciate the effort you put into this.",
  "I'm impressed by the depth of your knowledge.",
  "I couldn't agree more with what you've written.",
  "Brilliant post! Can't wait to read more from you.",
  "You've made this topic so easy to understand. Thank you!",
  "This is exactly what I was looking for. Thanks a bunch!",
  "Insightful post. Learned something new today.",
  "Your writing style is engaging and informative.",
  "Kudos to you for sharing such valuable information.",
  "I'm so glad I stumbled upon this post. It's gold!",
  "This is pure gold! Thanks for sharing your expertise.",
  "I'll definitely be sharing this with my friends. Great job!",
  "Your passion for the topic really shines through.",
  "Thank you for taking the time to write this.",
  "This post deserves way more recognition. It's amazing!",
  "I feel like I've just had a masterclass on this topic. Excellent job!",
  "You've answered all my questions perfectly. Thank you!",
  "This is exactly what I needed right now. Thank you!",
  "Incredible post! I'm bookmarking this for future reference.",
  "I've never seen this topic explained so clearly. Well done!",
  "Thank you for sharing your expertise with us. Much appreciated.",
  "This post has given me so much inspiration. Thank you!",
  "Your writing always delivers valuable insights. Thank you!",
  "This post exceeded my expectations. Great job!",
  "This is a must-read for everyone interested in this topic.",
  "I'm blown away by how informative this post is. Thank you!",
  "This post deserves all the praise it can get. Well done!",
  "Thank you for sharing your knowledge with us. It's invaluable.",
  "This post is a gem! Thank you for sharing your wisdom.",
  "I can't thank you enough for writing this. It's incredibly helpful.",
  "This post has made me look at things from a whole new perspective. Thank you!",
  "I'm in awe of your expertise. Thank you for sharing it with us.",
  "I've learned so much from reading this post. Thank you!",
  "This is hands down the best post I've read on this topic. Thank you!",
  "Your insights are truly eye-opening. Thank you for sharing them.",
  "I've been struggling with this topic, and your post has cleared up so much for me. Thank you!",
  "I've bookmarked this post for future reference. It's that good!",
  "This post is like a goldmine of information. Thank you for sharing!",
  "Your expertise shines through every word of this post. Thank you!",
  "I've shared this post with all my friends. It's too good not to share!",
  "This post has exceeded all my expectations. Thank you!",
  "I'm speechless. This post is just too good!",
  "This is exactly what I needed to read right now. Thank you!",
  "You've done an incredible job with this post. Thank you!",
  "Thank you for sharing your wisdom with us. It's truly appreciated.",
  "This post is a game-changer. Thank you!",
  "I've never read anything like this before. Thank you for opening my eyes!",
  "You've outdone yourself with this post. Thank you!",
  "This post deserves all the praise it can get. Thank you!",
  "I'm so grateful for this post. Thank you!",
  "This post is a masterpiece. Thank you!",
  "You're a true expert in your field. Thank you for sharing your knowledge!",
  "I've learned so much from reading this post. Thank you!",
  "This post has given me so much clarity. Thank you!",
  "Thank you for sharing your insights with us. It's truly appreciated.",
  "This post is pure gold. Thank you!",
  "I can't thank you enough for writing this. It's incredibly helpful!",
  "Your passion for the topic really shines through in this post. Thank you!",
  "This post has opened my eyes to so many new ideas. Thank you!",
  "You've done an amazing job with this post. Thank you!",
  "Thank you for sharing your expertise with us. It's invaluable!",
  "This post is a treasure trove of information. Thank you!",
  "I've learned more from this post than I have from months of research. Thank you!",
  "This post deserves all the praise it can get. Thank you!",
  "You're a true master of your craft. Thank you for sharing your knowledge!",
  "This post is a game-changer. Thank you!",
  "I'm blown away by the depth of knowledge in this post. Thank you!",
  "Thank you for taking the time to write this. It's greatly appreciated!",
  "This post is a must-read for anyone interested in this topic. Thank you!",
  "I can't thank you enough for sharing this with us. It's invaluable!",
  "This post has given me so much inspiration. Thank you!",
  "You've provided so much value with this post. Thank you!",
  "This post is exactly what I needed right now. Thank you!",
  "Your insights have made me see things in a whole new light. Thank you!",
  "This post is like a breath of fresh air. Thank you!",
  "Thank you for sharing your expertise with us. It's truly appreciated!",
  "This post has exceeded all my expectations. Thank you!",
  "I'm so grateful for this post. Thank you!",
  "You've done an incredible job with this post. Thank you!",
  "Thank you for taking the time to write this. It's greatly appreciated!",
  "This post is a masterpiece. Thank you!",
  "You're a true expert in your field. Thank you for sharing your knowledge!",
  "I've learned so much from reading this post. Thank you!",
  "This post has given me so much clarity. Thank you!",
  "Thank you for sharing your insights with us. It's truly appreciated!",
  "This post is pure gold. Thank you!",
  "I can't thank you enough for writing this. It's incredibly helpful!",
  "Your passion for the topic really shines through in this post. Thank you!",
  "This post has opened my eyes to so many new ideas. Thank you!",
  "You've done an amazing job with this post. Thank you!",
  "Thank you for sharing your expertise with us. It's invaluable!",
  "This post is a treasure trove of information. Thank you!"
];

module.exports = comments;
